---
title: "Predicting .. from Spotify Music"
author: Alyssia Goodwin & Nolan Guzman & Arthur Diaz
date: "May 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Data Input and Preprocessing 

```{r}
library(rpart)
library(rpart.plot)
library(maptree)
library(e1071)
# the following utility files can be found attached to the assignment
source("https://raw.githubusercontent.com/grbruns/cst383/master/lin-regr-util.R")
source("https://raw.githubusercontent.com/grbruns/cst383/master/class-util.R")

dat=read.csv("data.csv")
dat$X = NULL
dat$loudness=abs(dat$loudness)
dat$song_title = NULL
```

#Data Exploration

```{r}
dat$song_title=NULL
summary(dat)
```


<<<<<<< Updated upstream


=======
```{r, echo=TRUE}
fit=lm(danceability ~ acousticness+duration_ms+energy+instrumentalness+liveness+loudness+speechiness+tempo+valence, data=dat)
summary(fit)

par(mfrow=c(2,2))
plot(density(dat$danceability),col="red",main="Density of Features")
lines(density(dat$energy),col="green")
lines(density(dat$liveness),col="blue")
legend("topright",legend=c("Dance","Energy","Liveness"),col=c("Red","Blue","Green"),lty=1,cex=.7)

plot(ecdf(dat$danceability),col="red",main="ECDF of Features")
lines(ecdf(dat$energy),col="green")
lines(ecdf(dat$liveness),col="blue")
legend("bottomright",legend=c("Dance","Energy","Liveness"),col=c("Red","Blue","Green"),lty=1,cex=.7)

plot(danceability ~ liveness,data=dat, col="red",main="Danceability by Liveness")
plot(danceability ~ energy, data=dat, col="red",main="Danceability by Energy")

```

```{r,echo=TRUE}
set.seed(132)
split = split_data(heart)
tr_dat = split[[1]]
te_dat = split[[2]]

```